[build]
  command = "npm run build"
  publish = "dist/financial-organizer-front/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/angular-runtime"